import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>About Page</h1>
      </Layout>
    </div>
  );
};

export default About;
